set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CM_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA[0]}]
set_property PACKAGE_PIN W17 [get_ports {ADC_DATA[0]}]
set_property PACKAGE_PIN V15 [get_ports {ADC_DATA[1]}]
set_property PACKAGE_PIN AB21 [get_ports {ADC_DATA[2]}]
set_property PACKAGE_PIN AB22 [get_ports {ADC_DATA[3]}]
set_property PACKAGE_PIN AA21 [get_ports {ADC_DATA[4]}]
set_property PACKAGE_PIN AA20 [get_ports {ADC_DATA[5]}]
set_property PACKAGE_PIN AB20 [get_ports {ADC_DATA[6]}]
set_property PACKAGE_PIN AA19 [get_ports {ADC_DATA[7]}]
set_property PACKAGE_PIN AA18 [get_ports {ADC_DATA[8]}]
set_property PACKAGE_PIN AB18 [get_ports {ADC_DATA[9]}]
set_property PACKAGE_PIN T20 [get_ports {ADC_DATA[10]}]
set_property PACKAGE_PIN P20 [get_ports {ADC_DATA[11]}]
set_property PACKAGE_PIN W22 [get_ports {ADC_DATA[12]}]
set_property PACKAGE_PIN W21 [get_ports {ADC_DATA[13]}]
set_property PACKAGE_PIN T21 [get_ports {ADC_DATA[14]}]
set_property PACKAGE_PIN U21 [get_ports {ADC_DATA[15]}]


set_property PACKAGE_PIN F21 [get_ports {CM_DATA[0]}]
set_property PACKAGE_PIN G17 [get_ports {CM_DATA[1]}]
set_property PACKAGE_PIN G18 [get_ports {CM_DATA[2]}]
set_property PACKAGE_PIN G15 [get_ports {CM_DATA[3]}]
set_property PACKAGE_PIN G16 [get_ports {CM_DATA[4]}]
set_property PACKAGE_PIN H14 [get_ports {CM_DATA[5]}]
set_property PACKAGE_PIN M17 [get_ports {CM_DATA[6]}]
set_property PACKAGE_PIN J14 [get_ports {CM_DATA[7]}]
set_property PACKAGE_PIN H15 [get_ports {CM_DATA[8]}]
set_property PACKAGE_PIN J15 [get_ports {CM_DATA[9]}]
set_property PACKAGE_PIN H13 [get_ports {CM_DATA[10]}]
set_property PACKAGE_PIN J20 [get_ports {CM_DATA[11]}]
set_property PACKAGE_PIN H19 [get_ports {CM_DATA[12]}]
set_property PACKAGE_PIN J19 [get_ports {CM_DATA[13]}]
set_property PACKAGE_PIN G13 [get_ports {CM_DATA[14]}]
set_property PACKAGE_PIN J21 [get_ports {CM_DATA[15]}]


set_property IOSTANDARD LVCMOS33 [get_ports ADC_OUTCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CAL]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PDN]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_RST]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SDI]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SEN]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_SH_R]
set_property IOSTANDARD LVCMOS33 [get_ports CM_DVAL]
set_property IOSTANDARD LVCMOS33 [get_ports CM_FVAL]
set_property IOSTANDARD LVCMOS33 [get_ports CM_LVAL]
set_property IOSTANDARD LVCMOS33 [get_ports CM_PWR_DWN]
set_property IOSTANDARD LVCMOS33 [get_ports CM_SPARE]
set_property IOSTANDARD LVCMOS33 [get_ports CM_TXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]

set_property PACKAGE_PIN U22 [get_ports ADC_SCLK]
set_property PACKAGE_PIN W20 [get_ports ADC_SDI]
set_property PACKAGE_PIN V22 [get_ports ADC_SDO]
set_property PACKAGE_PIN T18 [get_ports ADC_SEN]
set_property PACKAGE_PIN W19 [get_ports ADC_SH_R]

set_property PACKAGE_PIN Y18 [get_ports ADC_CAL]
set_property PACKAGE_PIN Y21 [get_ports ADC_CLK]
set_property PACKAGE_PIN U15 [get_ports ADC_OUTCLK]
set_property PACKAGE_PIN V17 [get_ports ADC_PDN]
set_property PACKAGE_PIN Y19 [get_ports ADC_RST]

set_property PACKAGE_PIN D22 [get_ports CM_DVAL]
set_property PACKAGE_PIN J22 [get_ports CM_FVAL]
set_property PACKAGE_PIN K21 [get_ports CM_LVAL]
set_property PACKAGE_PIN D21 [get_ports CM_PWR_DWN]
set_property PACKAGE_PIN K22 [get_ports CM_SPARE]
set_property PACKAGE_PIN E22 [get_ports CM_TXCLK]


set_property IOSTANDARD LVCMOS33 [get_ports H1]
set_property IOSTANDARD LVCMOS33 [get_ports H2]
set_property IOSTANDARD LVCMOS33 [get_ports RG]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports XSG2]
set_property IOSTANDARD LVCMOS33 [get_ports XSUB]
set_property IOSTANDARD LVCMOS33 [get_ports XSG3]
set_property IOSTANDARD LVCMOS33 [get_ports XV1]
set_property IOSTANDARD LVCMOS33 [get_ports XV2]
set_property IOSTANDARD LVCMOS33 [get_ports XV3]
set_property PACKAGE_PIN J16 [get_ports UART_RX]
set_property PACKAGE_PIN F15 [get_ports UART_TX]
set_property PACKAGE_PIN A19 [get_ports H1]
set_property PACKAGE_PIN A18 [get_ports H2]
set_property PACKAGE_PIN C20 [get_ports RG]
set_property PACKAGE_PIN F18 [get_ports XSG2]
set_property PACKAGE_PIN C18 [get_ports XSG3]
set_property PACKAGE_PIN B18 [get_ports XSUB]
set_property PACKAGE_PIN E18 [get_ports XV1]
set_property PACKAGE_PIN C19 [get_ports XV2]
set_property PACKAGE_PIN B17 [get_ports XV3]
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property PACKAGE_PIN M17 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property PACKAGE_PIN W5 [get_ports LED]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports eth_rst_n]


set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[0]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[1]}]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[2]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[3]}]
#set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports eth_rx_ctl]



set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {eth_txd[0]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {eth_txd[1]}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports {eth_txd[2]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {eth_txd[3]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports eth_txc]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports eth_tx_ctl]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets eth_txc_OBUF]

set_property PACKAGE_PIN L16 [get_ports eth_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxc]
